AWSTemplateFormatVersion: "2010-09-09"
Description: This template creates a Nat gateway in each private subnet
Parameter:
  ExportVPC:
    Description: The name of the vpc stack
    Type: String

Resources:
  EIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: VPC
      Tags:
        - Key: Name
          Value: EIP1

  EIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: VPC
      Tags:
        - Key: Name
          Value: EIP2:

  PrivateSub1Natgateway:
    Type: AWS::EC2::NatGateway
      Properties:
        AllocationId: !GetAtt EIP1.AllocationId
        SubnetId: 
          fn::ImportValue: !Sub ${ExportVPC}-PrivateSub1
        Tags: 
          - Key: Name
            Value: PrivateSub1Natgateway

  PrivateSub2Natgateway:
    Type: AWS::EC2::NatGateway
      Properties:
        AllocationId: !GetAtt EIP2.AllocationId
        SubnetId: 
          fn::ImportVale: !Sub ${ExportVPC}-PrivateSub2
        Tags: 
          - Key: Name
            Value: PrivateSub2Natgateway
