---
AWSTemplateFormatVersion: "2010-09-09"
Description: Using a cloud formation template to create VPC for the Microservice application


Parameters:
# Parameters to create VPC and Subnets
  vpcCIDR:
    Description: IP range for the vpc
    Type: "string"
    Default: 10.0.0.0/16
  
  publicSubnet1CIDR:
    Description: IP range for public subnet 1
    Type: String
    Default: 10.0.1.0/24

  publicSubnet2CIDR:
    Description: IP range for public subnet 2
    Type: String
    Default: 10.0.2.0/24

  privateSubnet1CIDR:
    Description: IP range for private subnet 1
    Type: String
    Default: 10.0.3.0/24

  privateSubnet2CIDR:
    Description: IP range for private subnet 2
    Type: String
    Default: 10.0.4.0/24

# Parameter to determine how a user can ssh into an ec2
  SSHLocation:
    Description: The IP address range that can SSH to the EC2 instance
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
  

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 
        Ref: vpcCIDR
      EnableDnsHostnames: True
      EnableDnsSupport: True
      InstanceTenancy: default
      Tags: 
        - key: Name
          Value: app-vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: app-igw

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
       Ref: VPC
      InternetGatewayId:
       Ref: InternetGateway

  PublicSub1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 0
        - !GetAZs
          Ref: 'AWS::Region'
      CidrBlock: 
        Ref: publicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: public-subnet-1
      VpcId:
        Ref: VPC

  PublicSub2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 1
        - !GetAZs
          Ref: 'AWS::Region'
      CidrBlock: 
        Ref: publicSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: public-subnet-2
      VpcId:
        Ref: VPC


  PrivateSub1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 0
        - !GetAZs
          Ref: 'AWS::Region'
      CidrBlock: 
        Ref: privateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: Name
          Value: private-subnet-1
      VpcId:
        Ref: VPC

  PrivateSub2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 1
        - !GetAZs
          Ref: 'AWS::Region'
      CidrBlock: 
        Ref: privateSubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: Name
          Value: private-subnet-2
      VpcId:
        Ref: VPC

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: VPC
      Tags:
      - Key: Name
        Value: app-route-table1

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: VPC
      Tags:
      - Key: Name
        Value: app-route-table2
      

